#
# Site config for a jekyll project
#

# This will be the first part of the title tag for your site <title> site.name + page.title </title>
title: "Beard and Beanie, Bar Harbor, Maine web design."

# Populates the meta description for the site. Should be under 150 characters for best SEO purposes.
descripiton: "A creative workshop in Maine offering services in website design and development, archival digitization, database design and community management."

# Owner (organization or individual) of site content
author: "Beard and Beanie"

#url: "[http:// ]"
url: "http://beardandbeanie.com"

# Your UA tracking number (i.e 35858753-1) for Google Analytics. 
# If you comment this out, or don't fill out this parameter - Google analytics won't be included. 
googleID: UA-44030322-1

# Pagination variable for how many posts to show in a list
paginate: 10

# Style of permalinks
permalink: pretty
# Variable format options for URL styles below
# pretty                                          => /2009/04/29/slap-chop/index.html
# /:month-month:day-:year/:title.html/            => 04-29-2009/slap-chop.html
# /blog/:yearr/:month/:day/:title                 => /blog/2009/04/29/slap-chop/index.html

markdown: maruku
markdown_ext: markdown,mkd,mkdn,md

# To use PANDOC for markdown rendering
#markdown: pandoc
#pandoc:
#  format: html5

# UnComment once you have pygments installed. Used for code syntax highlighting.
pygments: true

# Add anything here you don't want copied to _site. By default anything with a leading underscore won't be copied over.
exclude: [Rakefile, simpleforminfo.pdf]
